version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:860061945305:task-definition/authorization:1"
        LoadBalancerInfo:
          ContainerName: "authorization"
          ContainerPort: "9000"
        PlatformVersion: "LATEST"